let config = {
    workType:[{
        text:"类型1",
        value:1,
    },{
        text:"类型2",
        value:2,
    },{
        text:"类型3",
        value:3,
    },{
        text:"类型4",
        value:4,
    }],
    newsType:[{
        text:"类型1",
        value:1,
    },{
        text:"类型2",
        value:2,
    },{
        text:"类型3",
        value:3,
    },{
        text:"类型4",
        value:4,
    }],
}
export default config;